#define SEPERATOR L"$"
#define RECORD_FILE "record.txt"

#define VK_SPACE_STR L"space"
#define VK_LBUTTON_STR L"mouseleft"
#define VK_RBUTTON_STR L"mouseright"
#define VK_MBUTTON_STR L"mousemid"
#define VK_RETURN_STR L"\n"
#define VK_BACK_STR L"backspace"
#define VK_TAB_STR L"tab"
#define VK_ESCAPE_STR L"esc"
#define VK_INSERT_STR L"ins"
#define VK_DELETE_STR L"del"
#define VK_LEFT_STR L"leftarrow"
#define VK_UP_STR L"uparrow"
#define VK_RIGHT_STR L"rightarrow"
#define VK_DOWN_STR L"downarrow"
#define VK_SNAPSHOT_STR L"printscreen"
#define VK_APPS_STR L"appsbutton"
#define VK_SLEEP_STR L"sleepbutton"

